version: 2
updates:
  # API dependencies
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
    reviewers:
      - "mortensieker"
    labels:
      - "dependencies"
      - "api"
    commit-message:
      prefix: "api"
      include: "scope"
    # Ignore patch updates
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    # Group all major + minor dependencies into one PR
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"

  # Web dependencies
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
    reviewers:
      - "mortensieker"
    labels:
      - "dependencies"
      - "web"
    commit-message:
      prefix: "web"
      include: "scope"
    # Ignore patch updates
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    # Group all major + minor dependencies into one PR
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    rebase-strategy: "auto"
    open-pull-requests-limit: 3
    reviewers:
      - "mortensieker"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Ignore patch updates
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    # Group all major + minor dependencies into one PR
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
